// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0V8Ik9-7tPsu3d1ZIOSXaXtdQzyBFyc',
    appId: '1:820215324945:web:36ef56c5d6a0bf04ae6cb0',
    messagingSenderId: '820215324945',
    projectId: 'maybackend-ec5d9',
    authDomain: 'maybackend-ec5d9.firebaseapp.com',
    storageBucket: 'maybackend-ec5d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYICCZuhLbF1FGcLFCU-KF5fKQHKQI-c',
    appId: '1:820215324945:android:efa1d410b3e862d3ae6cb0',
    messagingSenderId: '820215324945',
    projectId: 'maybackend-ec5d9',
    storageBucket: 'maybackend-ec5d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCKEfnczBhZpHVRHtIP4Bc2Ls4BAH1HrU',
    appId: '1:820215324945:ios:e34589bc5f1ecf32ae6cb0',
    messagingSenderId: '820215324945',
    projectId: 'maybackend-ec5d9',
    storageBucket: 'maybackend-ec5d9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCKEfnczBhZpHVRHtIP4Bc2Ls4BAH1HrU',
    appId: '1:820215324945:ios:e34589bc5f1ecf32ae6cb0',
    messagingSenderId: '820215324945',
    projectId: 'maybackend-ec5d9',
    storageBucket: 'maybackend-ec5d9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0V8Ik9-7tPsu3d1ZIOSXaXtdQzyBFyc',
    appId: '1:820215324945:web:f01c72d0d23c8b1eae6cb0',
    messagingSenderId: '820215324945',
    projectId: 'maybackend-ec5d9',
    authDomain: 'maybackend-ec5d9.firebaseapp.com',
    storageBucket: 'maybackend-ec5d9.firebasestorage.app',
  );
}
